# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI PIPELINE

on:
  pull_request:
    branches: [ "master" ]

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the job is now running on a ${{ runner.os }} server hosted by Github!"
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

  build:
    runs-on: ubuntu-latest
    needs: restore  # This job runs only after restore finishes
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies (use cache if available)
        run: dotnet restore
      - name: Build API
        run: dotnet build  SocialMediaBackend.API/SocialMediaBackend.API.csproj --no-restore --configuration Release
      - name: Build Azure Functions
        run: dotnet build SocialMediaBackend.Functions/SocialMediaBackend.Functions.csproj --no-restore --configuration Release
      - name: Upload API Build Atrifacts
        uses: actions/upload-artifact@v3
        with:
            name: api-build-output
            path: SocialMediaBackend.API/bin/Release/net8.0/
      - name: Upload FUnctions Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: functions-build-output
          path: SocialMediaBackend.Functions/bin/Release/net8.0/