# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI PIPELINE

on:
  pull_request:
    branches: [ "master" ]

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the job is now running on a ${{ runner.os }} server hosted by Github!"
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

  build:
    runs-on: ubuntu-latest
    needs: restore  # This job runs only after restore finishes
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies (use cache if available)
        run: dotnet restore
      - name: Build API
        run: dotnet build SocialMediaBackend.API/SocialMediaBackend.API.csproj --no-restore --configuration Release
      - name: Check build 
        run: echo "build successfull"
      - name: Build Azure Functions
        run: dotnet build SocialMediaBackend.Functions/SocialMediaBackend.Functions.csproj --no-restore --configuration Release
      - name: Check API Build Output is Not Empty
        run: |
            if [ -z "$(ls -A SocialMediaBackend.API/bin/Release/net8.0/)" ]; then
                echo "? API Build output is empty!"
                exit 1
            else
                echo "? API Build output is not empty."
            fi
      - name: Upload API Build Atrifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
            name: api-build-output
            path: ${{ github.workspace }}/SocialMediaBackend.API/bin/Release/net8.0/
      - name: Upload Functions Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: functions-build-output
          path: ${{ github.workspace }}/SocialMediaBackend.Functions/bin/Release/net8.0/
  test:
    runs-on: ubuntu-latest
    needs: build  # This job runs only after build finishes
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies (use cache if available)
        run: dotnet restore
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: bin/
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal